name: Deploy to Netlify

on:
  workflow_dispatch:
    inputs:
      deploy_production:
        description: 'Select if deploying to Production'
        required: true
        default: false
        type: boolean

  pull_request:
    paths:
      - 'src/**'
  push:
    branches:
      - master
    paths:
      - 'src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Preview
        if: |
          github.event_name == 'pull_request' || 
          (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_production == 'false')
        run: npm run netlify:preview
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Deploy to Production
        if: |
          (github.event_name == 'push' && github.ref == 'refs/heads/master') ||
          (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_production == 'true')
        run: npm run netlify:production
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
